# Generated by Django 4.2.11 on 2025-04-16 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendaPizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.pizzamodel')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.vendamodel')),
            ],
        ),
    ]
